### PR TITLE
Trying to add torchview

### PR DESCRIPTION
**Pull request by turian**

### CODE REVIEW

**Comment by albertfgu** [comment]
This looks a bit WIP so I won't merge anything yet, but happy to assist if this change is important.

Some questions:
- Why is the pytorch-lightning dependency included? And are the other dependencies needed? (maybe can add a comment explaining each one?)
- I don't remember why the original code has all these `.cuda()` calls, but is it okay to remove them? Are things being converted to CUDA elsewhere?

**Comment by turian** [comment]
@albertfgu apologies, I didn't actually mean to create a merge request into your branch. Rather to create a PR in my own fork. I was demonstrating to the author of torchview that there is some graphing bug in that library possibly caused by the opt_einsum library.

**Comment by turian** [comment]
@albertfgu BTW, lightning dependency was added because `s4.py` imports it.

**Comment by albertfgu** [comment]
Oh you're right, I forgot that it's used just for a multi-device utility.

**Pull request closed without merging**
